upstreams:
  groups:
    default:
    - cloudflare-dns.com:853
    - tcp-tls:fdns1.dismail.de:853
    - dns.google:853

blocking:
  blockType: zeroIP
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads

bootstrapDns:
  - tcp+udp:1.1.1.1
  - https://1.1.1.1/dns-query
  - upstream: https://dns.digitale-gesellschaft.ch/dns-query
    ips:
      - 185.95.218.42

ports:
  dns: 53
  http: 4000

log:
  level: info
