services:
  blocky:
    container_name: blocky
    hostname: blocky
    image: spx01/blocky:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000"
    environment:
      - TZ=Europe/Berlin  # Change this to your timezone
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - blocky_net

networks:
  blocky_net:
    driver: bridge
