services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    environment:
      TZ: Europe/Berlin
      CRON_MIN: '*/30'
    ports:
      - 8079:80
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    restart: unless-stopped

